// Detects when code is pasted into editor
let lastPastedCode = '';
let aiCodePatterns = [
  /\/\/ AI-generated/i,
  /# Generated by ChatGPT/i,
  /\/\* This code was generated by/i,
  /function.*generated/i,
  /\/\/ Source: ChatGPT|Claude|Gemini/i
];

// Detect paste events
document.addEventListener('paste', async (e) => {
  const pastedText = e.clipboardData.getData('text');
  
  if (isLikelyCode(pastedText)) {
    lastPastedCode = pastedText;
    
    // Check if it's AI-generated
    const isAIGenerated = await analyzeIfAIGenerated(pastedText);
    
    if (isAIGenerated || pastedText.length > 50) {
      // Show notification
      showNotification(pastedText);
      
      // Send to background for analysis
      chrome.runtime.sendMessage({
        type: 'CODE_PASTED',
        code: pastedText,
        timestamp: Date.now(),
        url: window.location.href
      });
    }
  }
});

// Detect code characteristics
function isLikelyCode(text) {
  const codeIndicators = [
    /function\s+\w+\s*\(/,
    /class\s+\w+/,
    /def\s+\w+\s*\(/,
    /const\s+\w+\s*=/,
    /import\s+[\w{},\s]+from/,
    /if\s*\(.*\)\s*{/,
    /<\w+.*>/,
    /\w+\.\w+\(/
  ];
  
  return codeIndicators.some(pattern => pattern.test(text)) || 
         (text.includes('{') && text.includes('}')) ||
         (text.includes('(') && text.includes(')') && text.includes(';'));
}

// AI-generated code detection
async function analyzeIfAIGenerated(code) {
  // Check for common AI patterns
  if (aiCodePatterns.some(pattern => pattern.test(code))) {
    return true;
  }
  
  // Check for suspicious patterns
  const suspiciousPatterns = [
    /\/\/ Here's|Here is/i,
    /\/\/ This (code|function|class)/i,
    /# Note:|# Important:/i,
    /\/\/ Example usage:/i,
    /\/\/ Replace.*with your/i,
    /(TODO|FIXME|XXX):.*implement/i
  ];
  
  return suspiciousPatterns.some(pattern => pattern.test(code));
}

// Show inline notification
function showNotification(code) {
  const notification = document.createElement('div');
  notification.id = 'ai-debugger-notification';
  notification.innerHTML = `
    <div style="
      position: fixed;
      top: 20px;
      right: 20px;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 16px 24px;
      border-radius: 12px;
      box-shadow: 0 8px 32px rgba(0,0,0,0.3);
      z-index: 999999;
      font-family: 'Segoe UI', system-ui, sans-serif;
      animation: slideIn 0.3s ease-out;
    ">
      <div style="display: flex; align-items: center; gap: 12px;">
        <div style="font-size: 24px;">🔍</div>
        <div>
          <div style="font-weight: 600; font-size: 14px;">AI Code Detected</div>
          <div style="font-size: 12px; opacity: 0.9; margin-top: 4px;">
            Analyzing for potential issues...
          </div>
        </div>
      </div>
    </div>
  `;
  
  document.body.appendChild(notification);
  
  setTimeout(() => {
    notification.style.opacity = '0';
    notification.style.transition = 'opacity 0.3s';
    setTimeout(() => notification.remove(), 300);
  }, 3000);
}

// Listen for results from background
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.type === 'ANALYSIS_COMPLETE') {
    showAnalysisResult(message.result);
  }
});

function showAnalysisResult(result) {
  const panel = document.createElement('div');
  panel.id = 'ai-debugger-panel';
  panel.innerHTML = `
    <div style="
      position: fixed;
      bottom: 20px;
      right: 20px;
      width: 400px;
      max-height: 600px;
      background: white;
      border-radius: 16px;
      box-shadow: 0 12px 48px rgba(0,0,0,0.2);
      z-index: 999999;
      overflow: hidden;
    ">
      <div style="
        background: ${result.issues.length > 0 ? '#ef4444' : '#10b981'};
        color: white;
        padding: 16px;
        font-weight: 600;
      ">
        ${result.issues.length > 0 ? '⚠️ Issues Found' : '✅ Code Looks Good'}
      </div>
      <div style="padding: 16px; max-height: 500px; overflow-y: auto;">
        ${result.issues.length > 0 ? `
          <div style="margin-bottom: 16px;">
            <div style="font-weight: 600; margin-bottom: 8px;">Found ${result.issues.length} issue(s):</div>
            ${result.issues.map(issue => `
              <div style="
                background: #fef2f2;
                border-left: 4px solid #ef4444;
                padding: 12px;
                margin-bottom: 8px;
                border-radius: 4px;
              ">
                <div style="font-weight: 500; color: #991b1b;">${issue.type}</div>
                <div style="font-size: 13px; color: #666; margin-top: 4px;">${issue.message}</div>
                ${issue.fix ? `
                  <div style="margin-top: 8px; font-size: 12px;">
                    <div style="font-weight: 500; color: #059669;">Suggested Fix:</div>
                    <pre style="
                      background: #f0fdf4;
                      padding: 8px;
                      border-radius: 4px;
                      overflow-x: auto;
                      margin-top: 4px;
                    ">${issue.fix}</pre>
                  </div>
                ` : ''}
              </div>
            `).join('')}
          </div>
        ` : `
          <div style="text-align: center; padding: 20px;">
            <div style="font-size: 48px;">🎉</div>
            <div style="margin-top: 8px; color: #666;">No issues detected!</div>
          </div>
        `}
        ${result.suggestions.length > 0 ? `
          <div style="margin-top: 16px;">
            <div style="font-weight: 600; margin-bottom: 8px;">💡 Suggestions:</div>
            ${result.suggestions.map(suggestion => `
              <div style="
                background: #eff6ff;
                padding: 10px;
                margin-bottom: 8px;
                border-radius: 4px;
                font-size: 13px;
                color: #1e40af;
              ">${suggestion}</div>
            `).join('')}
          </div>
        ` : ''}
      </div>
      <div style="
        padding: 12px 16px;
        border-top: 1px solid #e5e7eb;
        display: flex;
        gap: 8px;
      ">
        <button onclick="this.closest('#ai-debugger-panel').remove()" style="
          flex: 1;
          padding: 8px;
          background: #f3f4f6;
          border: none;
          border-radius: 6px;
          cursor: pointer;
          font-weight: 500;
        ">Close</button>
        <button onclick="navigator.clipboard.writeText('${JSON.stringify(result.fixedCode)}'); alert('Fixed code copied!')" style="
          flex: 1;
          padding: 8px;
          background: #667eea;
          color: white;
          border: none;
          border-radius: 6px;
          cursor: pointer;
          font-weight: 500;
        ">Copy Fixed Code</button>
      </div>
    </div>
  `;
  
  document.body.appendChild(panel);
}
